FROM rocker/rstudio

RUN apt-get update && apt-get install -y libxml2-dev zlib1g-dev unixodbc unixodbc-dev
RUN Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite("BiocInstaller")'
RUN install2.r --error RODBC devtools 
RUN install2.r --error knitr rmarkdown formatR

RUN export ADD=shiny && bash /etc/cont-init.d/add


RUN Rscript -e 'devtools::install_version("dplyr", version = "0.5.0"); devtools::install_github("vertica/DistributedR", subdir = "vRODBC"); devtools::install_github("vertica/vertica.dplyr")'
RUN install2.r --error shinycssloaders shinythemes
RUN sed -i '/site_dir/c\app_dir /srv/shiny-server/devcamp;' /etc/shiny-server/shiny-server.conf
RUN mkdir /srv/shiny-server/devcamp && chmod 777 /srv/shiny-server/devcamp && ln -s /srv/shiny-server/devcamp /home/rstudio/shiny
RUN service shiny-server reload
RUN install2.r --error microbenchmark

ADD ./vertica-client*.tar.gz /
ADD ./odbc*.ini /etc/

